# ChangeMe. Update according to setup.
# Set the particle type.
# /gps/particle e-

# Set the source position as well as its dimension
#/gps/pos/centre 0 100 0 um
#/gps/pos/type Volume
#/gps/pos/shape Para
#/gps/pos/halfy 0.5 mm
#/gps/pos/halfx 4.5 mm
#/gps/pos/halfz 4.5 mm


# Set particle momentum direction and energy spectrum
#/gps/direction 0 -1 0
#/gps/ene/type Gauss
#/gps/ene/min 0 MeV
#/gps/ene/max 1 MeV